var time_str;

$(function() {
  return $.getJSON("./sas.json", function(data) {
    var band, band_text, div, div_p, e, flag, i, j, k, l, len, len1, len2, len3, n, next, next_band, next_date, now, place, ref, ref1, ref2, results, s, time_text;
    now = new Date();
    ref = ["sorami", "B3", "3F9", "4F5", "hiroba", "sky", "f350"];
    results = [];
    for (j = 0, len1 = ref.length; j < len1; j++) {
      place = ref[j];
      len = data["timetable"][place].length;
      div_p = $("#" + place);
      flag = false;
      ref1 = data["timetable"][place];
      for (i = k = 0, len2 = ref1.length; k < len2; i = ++k) {
        band = ref1[i];
        s = new Date(band["start_time"]);
        e = new Date(band["end_time"]);
        if (now >= s && now < e) {
          flag = true;
          div = div_p.find(".now");
          time_text = time_str(s) + "〜" + time_str(e);
          div.find(".time").text(time_text);
          band_text = band["band"];
          if (band["circle"]) {
            band_text += "（" + band["circle"] + "）";
          }
          div.find(".band").text(band_text);
          n = Math.max(0, Math.min(len - (i + 1), 4));
          if (n > 0) {
            ref2 = data["timetable"][place].slice(i + 1, +(i + n) + 1 || 9e9);
            for (l = 0, len3 = ref2.length; l < len3; l++) {
              next_band = ref2[l];
              next_date = new Date(next_band["start_time"]);
              if (now.getDate() === next_date.getDate()) {
                band_text = next_band["band"];
                if (next_band["circle"]) {
                  band_text += "（" + next_band["circle"] + "）";
                }
                next = "→ " + (time_str(next_date)) + " " + band_text + " ";
                div_p.find(".next").append($('<p>').text(next));
              }
            }
          }
          break;
        }
      }
      if (!flag) {
        results.push(div_p.find(".band").text("ただいま演奏していません"));
      } else {
        results.push(void 0);
      }
    }
    return results;
  });
});

time_str = function(date) {
  return ("0" + date.getHours()).slice(-2) + ":" + ("0" + date.getMinutes()).slice(-2);
};

// ---
// generated by coffee-script 1.9.2
