var date_str;

$(function() {
  var places;
  places = {
    "sorami": "ソラミ坂ひろば",
    "B3": "地下3階エントランススペース",
    "3F9": "3階9番地エスカレーター横",
    "4F5": "4階5番地ツリービレッジエントランス横",
    "hiroba": "ソラマチひろば",
    "sky": "スカイアリーナ",
    "f350": "タワー天望デッキフロア350"
  };
  $.getJSON("./sas.json", function(data) {
    var band, band_text, bands, div, i, j, k, l, len, len1, len2, place, ref, ref1, results, timetable;
    bands = [];
    ref = ["sorami", "B3", "3F9", "4F5", "hiroba", "sky", "f350"];
    for (j = 0, len = ref.length; j < len; j++) {
      place = ref[j];
      ref1 = data["timetable"][place];
      for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
        band = ref1[i];
        band["place"] = place;
      }
      bands = bands.concat(data["timetable"][place]);
    }
    bands.sort(function(a, b) {
      if (a["start_time"] >= b["start_time"]) {
        return 1;
      } else {
        return -1;
      }
    });
    timetable = $("#timetable");
    results = [];
    for (l = 0, len2 = bands.length; l < len2; l++) {
      band = bands[l];
      div = $('<div>').addClass('info');
      band_text = date_str(new Date(band["start_time"])) + "〜 " + band["band"];
      if (band["circle"]) {
        band_text += "<span class='circle'>（" + band["circle"] + "）</span>";
      }
      div.append($('<p>').addClass("bandname").append(band_text));
      div.append($('<p>').addClass("date").text("＠" + places[band["place"]]));
      results.push(timetable.append(div));
    }
    return results;
  });
  $("#search_text").keyup(function() {
    var result;
    result = $(".info:contains('" + ($(this).val()) + "')");
    result.show();
    return $(".info").not(result).hide();
  });
  return $("#search_reset").click(function() {
    $("#search_text").val("");
    return $(".info").show();
  });
});

date_str = function(date) {
  return date.getDate() + "日" + ("0" + date.getHours()).slice(-2) + ":" + ("0" + date.getMinutes()).slice(-2);
};

// ---
// generated by coffee-script 1.9.2
